### ISSUE TITLE
How to get the status code of the API response

### ISSUE THREAD

**Issue by redjolr** [voucherifyio/voucherify-js-sdk#187] opened 2023-02-21 11:07 UTC
Hello everyone. I have a question regarding the HTTP responses and how I can inspect the status code.

Let's say we have this code

```
return this.client.customers
      .get(customerId)
      .then((response: CustomerObject) => response as VoucherifyCustomer)
      .catch((error) => {
          // Handle error
      });
```

How can we inspect the status code of the response when there is an error?

**Comment by darekg11** [comment] 2023-02-21 12:30
Hello @redjolr 
The status code should always be included in the `code` property of the error object.
Example:
```
voucherify.customers
	.get('non_existing_customer')
	.then(result => {
		console.log('Result: ', result)
	})
	.catch(error => {
		console.log('Error: %j', error.code)
	})
```

Output is:
```
Error: 404
```

I am closing this issue for now, feel free to re-open in case of more questions

**Comment by redjolr** [comment] 2023-02-21 14:35
Hello @darekg11 
But why haven't you guys typed this `code` field? It does not exist in any type definitions that I looked at (like VoucherifyError for example)

**Comment by darekg11** [comment] 2023-02-23 14:26
@redjolr Let me reopen this issue, I will try to take a look at it tomorrow and see if we can release new version with patch bump 🤔

**Comment by darekg11** [comment] 2023-02-24 12:09
Dear @redjolr I did some investigation and came up with following conclusions:
1. In case of promise rejection type is always any, it can not be casted: https://github.com/Microsoft/TypeScript/issues/6283#issuecomment-240804072 + https://github.com/microsoft/TypeScript/issues/39680#issuecomment-1328976622 so I could add `VoucherifyAPIError` type but person using SDK would still need to explictly cast `error` in `catch` like so:
```
.catch((error: VoucherifyAPIError)
```
which I find cumbersome 🤔 

2. Even in case of solution mentioned above the error is not always going to be related to Voucherify because in case of network failure, ie: timeout -  error is going to come back from `axios` itself so it won't have any of Voucherify related fields.

I don't have a strong opinion on how this should be approached.

**Comment by darekg11** [comment] 2023-02-24 12:28
@redjolr do you mean that AxiosError should be thrown instead of that current custom object?
If so then this is going to be a breaking change and I would like to avoid that

**Comment by darekg11** [comment] 2023-02-24 12:44
Generally speaking if there is connection error, for example: timeout / not reachable DNS or whatever else then error thrown will indeeed be the one from `Axios`

See example:
```
const { VoucherifyServerSide } = require('@voucherify/sdk')

const voucherify = VoucherifyServerSide({
	applicationId: '5452e923-810c-4880-83fb-65202fab8e28',
	secretKey: '6a0f56de-b5a8-4893-bedd-79711134108b',
	apiUrl: 'https://notasdadadawe.com',
})

voucherify.customers
	.get('non_existing_customer')
	.then(result => {
		console.log('Result: ', result)
	})
	.catch(error => {
		console.log(error)
	})

```

```
....long error
    _currentUrl: 'https://notasdadadawe.com/v1/customers/non_existing_customer',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
````
In such case, the error is AxiosError, in any other case when request reached the API and there was no timeout then rejected errror should always contain `code` field.

I don't really see a way to type all of this to make it work in all cases.

**Closed by darekg11** 2023-02-24 12:44 UTC

**Comment by redjolr** [comment] 2023-02-24 13:01
@darekg11  Thank you for your insight to the problem. However we still have the problem of the untyped `code` field. I would suggest to improve the VoucherifyError type like this:

```
VoucherifyError {
  code?: HttpStatusCode,
  name: string;
  message: string;
  stack?: string;
}
```

In addition, you can include the underlying error that causes the `VoucherifyError` in another field like this:
```
VoucherifyError {
  code?: HttpStatusCode,
  name: string;
  message: string;
  stack?: string;
  cause: AxiosError | unknown;
}
```

The `cause` field would contain the original error. In this way, you can expose the original error, without causing a breaking change as you mentioned in one of your previous comments.

**Comment by darekg11** [comment] 2023-02-24 13:12
@redjolr Thank your for your insights
It's still going to be breaking change for some people that might right now check if error has `isAxiosError` property.
In your approach (if I understand you correctly), this would no longer works since that would be now under `cause` property.
On top of that I just assumed people use `isAxiosError` field, they still might rely on some other field and it's hard to provide it all

**Comment by redjolr** [comment] 2023-02-24 13:15
@darekg11 Ok, but can you at the very least add the optional `code?: HttpStatusCode,` field to `VoucherifyError` ?

**Comment by darekg11** [comment] 2023-02-24 13:19
@redjolr yes that is okay, I was trying to come up with solution to throw only single error in all of those cases to not require devs to do (for simplicity):
```
error: VouchieryError | AxiosError
```
but it's impossible without breaking change

**Comment by darekg11** [comment] 2023-02-24 13:21
`HttpStatusCode` won't be added.
We really do not want add any extra dependencies to that SDK, it's just going to be a simple `number` type

**Comment by redjolr** [comment] 2023-02-24 13:23
> `HttpStatusCode` won't be added. We really do not want add any extra dependencies to that SDK, it's just going to be a simple `number` type

Yeah that's ok. Just `number` is enough

**Comment by amado10** [comment] 2023-02-24 13:27
+1 @redjolr 
I also need this, otherwise, I cannot handle errors correctly.

**Comment by ActionSeeker** [comment] 2023-02-24 13:31
+1 @redjolr

**Comment by darekg11** [comment] 2023-02-27 09:23
Hello @redjolr @ActionSeeker @amado10
Could you please take a look at following pull request: https://github.com/voucherifyio/voucherify-js-sdk/pull/188 to make sure that it solves your issue?

**Comment by redjolr** [comment] 2023-02-27 10:05
@darekg11 Thanks for the PR. I see that you only improved the typing of the VoucherifyError. I take it that you are not planning to add the `cause: AxiosError | unknown;` field inside the VoucherifyError?

**Comment by redjolr** [comment] 2023-02-27 10:16
@darekg11 It is useful to inspect the HttpError body response. We would like to log that. That would be very useful when we face a critical error in Production to understand what caused it

**Comment by redjolr** [comment] 2023-02-27 10:24
@darekg11 Also if I have to deal with a next version major bump of the SDK, I may as well create an API client layer by myself right now, then write the code twice to

**Comment by darekg11** [comment] 2023-02-27 10:30
@redjolr I will add `cause` field.
Major bump won't happen anytime soon, I am just noting stuff down as it comes to make sure that everything is covered.

**Comment by redjolr** [comment] 2023-02-27 10:35
@darekg11 Greatly appreciated :pray:

**Comment by darekg11** [comment] 2023-02-27 11:45
@redjolr Sorry I am not 100 % convinced to including bare axios error object by default in `VouchierfyError`
The downside for me is that for all current user of this SDK this would start printing plaintext used API Keys to console if somebody is doing straight:
`console.log(error)`

And for some of our customer this might be treated as sensitive data leak.

Would you be OK with new option passed to SDK that you must set explicitly to `true` in order to have that field exposed?

**Comment by darekg11** [comment] 2023-02-27 12:45
@redjolr I have pushed commit: 7dbd4678c040a9828d52bcd83011360318c8de7f
Please let me know if this is sufficient solution for you

**Comment by darekg11** [comment] 2023-02-27 15:10
Hello @redjolr @ActionSeeker @amado10

SDK in version `2.1.7` was released and should be available in NPM registry shortly.
This release contains changes from:
https://github.com/voucherifyio/voucherify-js-sdk/pull/188
https://github.com/voucherifyio/voucherify-js-sdk/pull/190

Mainly:
- proper typing of `VoucherifyError`
- possibility to include root cause Axios error in `VoucherifyError` via property `exposeErrorCause` - you can read more here: https://github.com/voucherifyio/voucherify-js-sdk#-error-handling

Thank you for your patience and your feedback
